version: '2.27'

   
services: 
  nginx1:
    image: nginx
    restart: always  #每次总是启动
    networks: 
      - nginx-net
    volumes:
      - c:/data/nginx/html1:/usr/share/nginx/html
    ports:
      - "8888:80"
  nginx2:
    image: nginx
    restart: always  #每次总是启动
    networks: 
      - nginx-net
    volumes:
      - c:/data/nginx/html2:/usr/share/nginx/html
    ports:
      - "9999:80"

networks:
  nginx-net:
    driver: bridge
    
